### ISSUE TITLE
Improve instructions for ASK CLI deployment

### ISSUE THREAD

**Issue by habuma** [alexa-samples/skill-sample-java-premium-hello-world#2]
May I suggest that the documentation/instructions be improved to cover ASK CLI deployment as well as how to properly set timeout/memory requirements in the AWS Lambda function?

Backstory: I created a project based on this repository using `ask new` and selecting "Java". Then, after changing only the invocation name in the interaction model, I did `ask deploy`, which took care of almost everything for me. But when I tried launching the skill, it took a few moments and then failed. After much debugging (hindered by lack of a Log4j2 configuration) I figured out that it was timing out when invoking the Lambda function.

By default the timeout was set to 3 seconds, but I found that if I set it to 12 seconds or higher, it would work fine (at least for the unaltered fulfillment code). Even so, the default memory allotted to the function was 128M. I've not taken time to find an optimal value, but I found that bumping it up to 2048M (or even higher) will enable the function to launch faster and thus reduce the need for a longer timeout.

I'll be happy to submit a PR with such changes, but am unable to do so at the moment. So I'm creating this issue now in case someone else can get to it before I can.

**Comment by aszk** [comment]
Hello, thank you for your report. This should be taken care of by https://github.com/alexa/ask-cli/issues/370. Please report to ASK CLI issue if the issue still persists.
